// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    Demo: typeof import('./src/components/Demo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MdiAbTesting: typeof import('~icons/mdi/ab-testing')['default']
    PhActivityLight: typeof import('~icons/ph/activity-light')['default']
    PhAppleLogoFill: typeof import('~icons/ph/apple-logo-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
